
import java.awt.event.KeyEvent;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maxwell
 */
public class Output extends javax.swing.JFrame {

    /**
     * Creates new form Output
     */
    public Output() {
        initComponents();
        setResizable(false);
        setSize(726, 376);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        protein = new java.awt.TextField();
        poutput = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bbutton = new javax.swing.JButton();
        ibutton = new javax.swing.JButton();
        abutton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Category Picker");
        setIconImages(null);
        setName("JFrame2"); // NOI18N
        setPreferredSize(new java.awt.Dimension(730, 380));
        getContentPane().setLayout(null);

        protein.setBackground(new java.awt.Color(51, 51, 51));
        protein.setForeground(new java.awt.Color(240, 240, 240));
        protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proteinActionPerformed(evt);
            }
        });
        protein.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                proteinKeyTyped(evt);
            }
        });
        getContentPane().add(protein);
        protein.setBounds(590, 100, 40, 20);

        poutput.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        poutput.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(poutput);
        poutput.setBounds(550, 140, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Result:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(510, 140, 70, 30);

        button1.setBackground(new java.awt.Color(51, 51, 51));
        button1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        button1.setForeground(new java.awt.Color(240, 240, 240));
        button1.setLabel("Enter");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(510, 190, 38, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Enter Weight (KG):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 100, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Protein Intake per Day");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(540, 50, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Choose Category:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 40, 260, 40);

        bbutton.setBackground(new java.awt.Color(0, 0, 0));
        bbutton.setForeground(new java.awt.Color(240, 240, 240));
        bbutton.setText("Beginner");
        bbutton.setName(""); // NOI18N
        bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(bbutton);
        bbutton.setBounds(130, 90, 110, 23);

        ibutton.setBackground(new java.awt.Color(0, 0, 0));
        ibutton.setForeground(new java.awt.Color(240, 240, 240));
        ibutton.setText("Intermediate");
        ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(ibutton);
        ibutton.setBounds(130, 130, 110, 23);

        abutton1.setBackground(new java.awt.Color(0, 0, 0));
        abutton1.setForeground(new java.awt.Color(240, 240, 240));
        abutton1.setText("Advanced");
        abutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(abutton1);
        abutton1.setBounds(130, 170, 110, 23);

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton1.setForeground(new java.awt.Color(240, 240, 240));
        jToggleButton1.setText("Back");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(30, 320, 70, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/black.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 20, 780, 380);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 740, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuttonActionPerformed
        // TODO add your handling code here:
        				//One
                                        BBeginner begin = new BBeginner();
                                        begin.setVisible(true);
                                        this.setVisible(false);
				
                                        
                                
							
                                
        
    }//GEN-LAST:event_bbuttonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       
         new myMain().setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibuttonActionPerformed
        // TODO add your handling code here:
        new BIntermediate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ibuttonActionPerformed

    private void abutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abutton1ActionPerformed
         new BAdvanced().setVisible(true);
        this.setVisible(false);
            
// TODO add your handling code here:
    }//GEN-LAST:event_abutton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String pro = protein.getText();
        double p = Double.parseDouble(pro);
        double k = 0.8;
        double e =  p * k;
        
       
        
        poutput.setText(String.valueOf(e) + " g");
        
    }//GEN-LAST:event_button1ActionPerformed

    private void proteinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proteinKeyTyped
        // TODO add your handling code here:
                char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume();
           
        }
    }//GEN-LAST:event_proteinKeyTyped

    private void proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proteinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Output().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abutton1;
    private javax.swing.JButton bbutton;
    private java.awt.Button button1;
    private javax.swing.JButton ibutton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel poutput;
    private java.awt.TextField protein;
    // End of variables declaration//GEN-END:variables

 
}
