
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maxwell
 */
public class Planks extends javax.swing.JFrame {
        int passed;
    /**
     * Creates new form Planks
     */
    public Planks() {
        initComponents();
        myMain ti = new myMain();
        Challenge challenge = new Challenge();
        setTitle("Challenge: Planks");

        setResizable(false);
        setSize(726, 400);
                Timer timer = new Timer();
       ;
       
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        strt = new java.awt.Button();
        stp = new java.awt.Button();
        save = new java.awt.Button();
        block = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        area = new java.awt.Label();
        w = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new java.awt.Label();
        btn = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Planks Challenge");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 290, 40);

        label1.setBackground(new java.awt.Color(0, 0, 0));
        label1.setForeground(new java.awt.Color(240, 240, 240));
        label1.setText("Time Set :");
        getContentPane().add(label1);
        label1.setBounds(20, 110, 60, 20);

        strt.setBackground(new java.awt.Color(204, 102, 0));
        strt.setForeground(new java.awt.Color(240, 240, 240));
        strt.setLabel("Start Timer");
        strt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strtActionPerformed(evt);
            }
        });
        getContentPane().add(strt);
        strt.setBounds(100, 330, 80, 24);

        stp.setBackground(new java.awt.Color(51, 51, 51));
        stp.setForeground(new java.awt.Color(240, 240, 240));
        stp.setLabel("Stop Timer");
        stp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stpActionPerformed(evt);
            }
        });
        getContentPane().add(stp);
        stp.setBounds(100, 330, 80, 24);

        save.setBackground(new java.awt.Color(51, 51, 51));
        save.setForeground(new java.awt.Color(240, 240, 240));
        save.setLabel("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(100, 330, 80, 24);

        block.setAlignment(java.awt.Label.CENTER);
        block.setBackground(new java.awt.Color(204, 102, 0));
        block.setFont(new java.awt.Font("Lucida Console", 0, 48)); // NOI18N
        block.setForeground(new java.awt.Color(240, 240, 240));
        block.setText("0");
        getContentPane().add(block);
        block.setBounds(470, 10, 240, 110);

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("USER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 60, 70, 14);

        area.setAlignment(java.awt.Label.CENTER);
        area.setBackground(new java.awt.Color(0, 0, 0));
        area.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(area);
        area.setBounds(20, 80, 110, 30);

        w.setAlignment(java.awt.Label.CENTER);
        w.setBackground(new java.awt.Color(0, 0, 0));
        w.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(w);
        w.setBounds(80, 110, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tunga", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("<html>\n<p>Set Your Plank Record</p>\n\n</html>\n");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 190, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/pushups (1).gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 120, 240, 120);

        time.setAlignment(java.awt.Label.CENTER);
        time.setBackground(new java.awt.Color(204, 102, 0));
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        time.setFont(new java.awt.Font("Lucida Console", 0, 50)); // NOI18N
        time.setForeground(new java.awt.Color(240, 240, 240));
        time.setText("0");
        getContentPane().add(time);
        time.setBounds(470, 10, 240, 110);

        btn.setBackground(new java.awt.Color(153, 102, 0));
        btn.setForeground(new java.awt.Color(240, 240, 240));
        btn.setLabel("Back");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn);
        btn.setBounds(620, 330, 43, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/planksbckgtrnd.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void strtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strtActionPerformed
        // TODO add your handling code here:

        strt.setVisible(false);
        stp.setVisible(true);
        save.setVisible(false);
        btn.setVisible(false);
        Timer timer = new Timer();

        TimerTask task = new TimerTask()
        {
            @Override
            public void run()

            {
                
                passed++;
                time.setText(String.valueOf(passed));
            }

        };
        timer.scheduleAtFixedRate(task, 0, 1000);//1000ms = 1 s

    }//GEN-LAST:event_strtActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        myMain begin = new myMain();
        Challenge challenge = new Challenge();

        
    
        String getTime = w.getText();
        challenge.postTime1((getTime)) ;

        String uname =  area.getText();
        String test = "";


        challenge.postData1(uname);

        challenge.setVisible(true);
        this.setVisible(false);

        //String getRep = repinput.getText();
        //challenge.postRep(getRep);

    }//GEN-LAST:event_btnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:

      //  int get = Integer.valueOf(username);

        Challenge challenge = new Challenge();
        //        int getRep = Integer.valueOf(repinput.getText());
        //        challenge.postRep(getRep);
        int getTime = Integer.valueOf(w.getText());
        String uname = area.getText();

        challenge.setVisible(true);
        this.setVisible(false);

        Ranking ranking = new Ranking();

        PushUpChallenge puc = new PushUpChallenge();
        myMain begin = new myMain();
        Log log = new Log();

        int rep = 0;
        String time = w.getText();
        String name = area.getText();
        ranking.postTime1(rep, time, name);

        
        String timelog = w.getText();
       

        challenge.postData(uname);
        challenge.postTime(getTime);

        puc.time.setVisible(false);

        save.setVisible(false);
        stp.setVisible(false);
        strt.setVisible(false);

        try {
            JLabel[] labels = null;
            String replog = null;
            log.postData3(name, replog, timelog, labels);

        } catch (IOException ex) {
            //   Logger.getLogger(Challenge.class.getName()).log(Level.SEVERE, null, ex);
        }

        //int maxtime = w.getText();

    }//GEN-LAST:event_saveActionPerformed

    private void stpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stpActionPerformed
        Object passed = null;
        // TODO add your handling code here:

        w.setText(String.valueOf(passed));
        String rec = String.valueOf(w.getText());

        time.setText(String.valueOf(rec));

        save.setVisible(true);
        stp.setVisible(false);
        strt.setVisible(false);

        time.setVisible(false);
        block.setVisible(true);
        save.setVisible(true);

      
        //gshow1.setVisible(true);

    }//GEN-LAST:event_stpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    java.awt.Label area;
    private java.awt.Label block;
    private java.awt.Button btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Label label1;
    private java.awt.Button save;
    private java.awt.Button stp;
    private java.awt.Button strt;
    public java.awt.Label time;
    java.awt.Label w;
    // End of variables declaration//GEN-END:variables
}
